version: '3.1'

services:
  backend_web:
    restart: always
    environment:
      _UVICORN_HOST: "0.0.0.0"
      _UVICORN_PORT: 8001
      _REDIS_HOST: "redis"
    build:
      context: .
      dockerfile: DockerfileWeb
    networks:
      - backend
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - "./app/.env:/backend/app/.env"
    ports:
      - 8000:8001

  backend_tg:
    restart: always
    environment:
      _REDIS_HOST: "redis"
    build:
      context: .
      dockerfile: DockerfileTG
    networks:
      - backend
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - "./app/.env:/backend/app/.env"

  redis:
    image: redis:7.2.3-bookworm
    restart: always
    # ports:
    #   - "6379:6379"
    command: redis-server --save 20 1
    volumes:
      - ./app/data/redis/:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    networks:
      - backend

networks:
  backend:
    name: backend
